# HARD-NEGATIVE MINING parameters

model_name: "sentence-transformers/all-MiniLM-L6-v2"
model_type: "hf"
query_prefix: "query:"
passage_prefix: "passage:"
api_key: "your api key here"
truncate: "END"
hard_negatives_to_mine: 4
hard_neg_mining_algorithm: "topk_percpos"
percpos: 0.95


# SEMANTIC CLUSTERING parameters
min_number_clusters: 10
cluster_output_dir: "/workspace/output/clusters"
logger_output_dir: "/workspace/output/logs"
